"""empty message

Revision ID: 11a1ad50ac85
Revises: 2d23d7e3f8a1
Create Date: 2024-07-03 17:39:07.351044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1ad50ac85'
down_revision = '2d23d7e3f8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
