"""empty message

Revision ID: 1eed321785a9
Revises: 94979062e2f2
Create Date: 2024-07-03 21:27:07.906630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eed321785a9'
down_revision = '94979062e2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
