"""empty message

Revision ID: 2d23d7e3f8a1
Revises: f653e752b95b
Create Date: 2024-07-03 17:33:40.874099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d23d7e3f8a1'
down_revision = 'f653e752b95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
