"""empty message

Revision ID: 4736ee3fccde
Revises: 1eed321785a9
Create Date: 2024-07-03 22:13:23.619238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4736ee3fccde'
down_revision = '1eed321785a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
