"""empty message

Revision ID: 51678a4cfa03
Revises: 791c5a046b6b
Create Date: 2024-05-08 19:07:48.489289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51678a4cfa03'
down_revision = '791c5a046b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('surname1', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('surname2', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'surname2')
    op.drop_column('users', 'surname1')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
