"""empty message

Revision ID: 63bf5a95e321
Revises: 51678a4cfa03
Create Date: 2024-05-08 20:21:23.754075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bf5a95e321'
down_revision = '51678a4cfa03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
