"""empty message

Revision ID: 68745a33b4c3
Revises: e09cc9cabf4d
Create Date: 2024-05-09 01:29:52.927892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68745a33b4c3'
down_revision = 'e09cc9cabf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
