"""empty message

Revision ID: 68a35ab42ee9
Revises: 11a1ad50ac85
Create Date: 2024-07-03 17:39:12.509677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a35ab42ee9'
down_revision = '11a1ad50ac85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
