"""empty message

Revision ID: 791c5a046b6b
Revises: 41795f2b44dc
Create Date: 2024-05-06 21:35:49.346020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791c5a046b6b'
down_revision = '41795f2b44dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
