"""empty message

Revision ID: 8f977ac950e4
Revises: 094dcf9dce39
Create Date: 2024-05-09 00:53:27.483750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f977ac950e4'
down_revision = '094dcf9dce39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subusers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('subusers', 'created_at')
    # ### end Alembic commands ###
