"""empty message

Revision ID: b16c157b1d74
Revises: 68745a33b4c3
Create Date: 2024-05-09 01:33:01.884021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16c157b1d74'
down_revision = '68745a33b4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
