"""empty message

Revision ID: b8a7a9a4c675
Revises: 68a35ab42ee9
Create Date: 2024-07-03 21:16:01.829956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8a7a9a4c675'
down_revision = '68a35ab42ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('subuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subuser_id'], ['subusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_id'), 'catalogs', ['id'], unique=False)
    op.create_index(op.f('ix_catalogs_name'), 'catalogs', ['name'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('subuser_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('published', 'unpublished', 'sold', 'reserved', 'deleted', name='itemstatus'), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['subuser_id'], ['subusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.add_column('sessions', sa.Column('subuser_id', sa.Integer(), nullable=True))
    op.drop_constraint('sessions_ibfk_1', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'subusers', ['subuser_id'], ['id'])
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_ibfk_1', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_column('sessions', 'subuser_id')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_catalogs_name'), table_name='catalogs')
    op.drop_index(op.f('ix_catalogs_id'), table_name='catalogs')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
