"""empty message

Revision ID: e09cc9cabf4d
Revises: 8f977ac950e4
Create Date: 2024-05-09 01:11:32.951028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09cc9cabf4d'
down_revision = '8f977ac950e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
