"""empty message

Revision ID: e3825d5476e8
Revises: 63bf5a95e321
Create Date: 2024-05-08 20:24:47.974011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3825d5476e8'
down_revision = '63bf5a95e321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('surname1', sa.String(length=16), nullable=True),
    sa.Column('surname2', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('hashed_password', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
