"""empty message

Revision ID: f653e752b95b
Revises: 3664ae1be588
Create Date: 2024-07-03 17:27:55.540863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f653e752b95b'
down_revision = '3664ae1be588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
